Problem 1: Basic Numpy

In [15]:
# 1. Use arange to create a NumPy array with 100 equally spaced values in the range 0
# through 100 (not including 100). Name this NumPy array a

import numpy as np
a = np.arange(100)

In [21]:
# 2. Use arange to create a NumPy array with 10 equally spaced values in the range 0
# through 100 (not including 100). Name this NumPy array b.

b = np.arange(0, 100, 10)

In [13]:
# 3. Create a random two-dimensional array with the dimensions 10 by 10. Call this
# NumPy array c.

c = np.random.rand(10,10)

In [17]:
#4. Reshape a so that it is a two-dimensional array with the dimensions 10 by 10.

a = a.reshape(10,10)

In [18]:
# 5. Show the results of “a[4,5]” and explain the results in a comment.
a[4,5]
# The matrix starts with a value of 0 on the 0th index of both dimensions. There for the index will be the same as the numbers separated by a comma

45

In [19]:
# 6. Show the sum of c.

np.sum(c)

49.632830795528385

In [31]:
# 7. Show the transpose of b.
np.transpose(b)
# very funny :)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
# 8. Show the results of adding a and c

a + c

array([[ 0.82230709,  1.91364575,  2.28597371,  3.61125933,  4.58245464,
         5.46607506,  6.38698664,  7.402321  ,  8.8065476 ,  9.28970094],
       [10.58465506, 11.46760158, 12.85532213, 13.71997354, 14.03224251,
        15.7590987 , 16.36733497, 17.0131417 , 18.81560248, 19.82526765],
       [20.90532182, 21.30562391, 22.00604026, 23.2527421 , 24.52867754,
        25.14411686, 26.39928661, 27.56017477, 28.90879304, 29.63813205],
       [30.42830091, 31.60633312, 32.31178239, 33.08011875, 34.44505597,
        35.28996689, 36.29285416, 37.77307294, 38.68917246, 39.8120014 ],
       [40.77802954, 41.52957503, 42.38349186, 43.91185449, 44.30811549,
        45.49661244, 46.25640079, 47.1421214 , 48.90774101, 49.86071153],
       [50.91684828, 51.27733517, 52.5877166 , 53.7332151 , 54.86468654,
        55.44144017, 56.37492588, 57.43506749, 58.27739299, 59.00820184],
       [60.17063497, 61.14310701, 62.14960755, 63.38956515, 64.30687327,
        65.16889982, 66.81609164, 67.07300882

In [29]:
# 9. Show the results of multiplying a and c

a * c

array([[ 0.        ,  0.91364575,  0.57194743,  1.83377799,  2.32981855,
         2.33037531,  2.32191984,  2.816247  ,  6.45238081,  2.60730843],
       [ 5.84655063,  5.14361742, 10.26386552,  9.35965603,  0.45139507,
        11.3864805 ,  5.87735952,  0.22340895, 14.68084457, 15.68008541],
       [18.10643644,  6.41810208,  0.13288564,  5.81306819, 12.68826108,
         3.60292148, 10.38145199, 15.12471868, 25.44620513, 18.50582957],
       [12.84902742, 18.79632666,  9.97703647,  2.64391875, 15.13190306,
        10.14884121, 10.54274967, 28.60369892, 26.18855348, 31.66805444],
       [31.12118164, 21.71257637, 16.10665792, 39.20974321, 13.55708165,
        22.34755995, 11.79443631,  6.67970571, 43.57156871, 42.17486503],
       [45.84241409, 14.14409388, 30.56126308, 38.86040054, 46.69307311,
        24.27920916, 20.99584906, 24.798847  , 16.08879358,  0.48390885],
       [10.23809798,  8.72952781,  9.27566831, 24.54260423, 19.63988958,
        10.97848807, 53.862048  ,  4.89159081

In [32]:
# 10. Show the results of computing the dot product of a and c.

np.dot(a, c)

array([[ 25.42884403,  13.42230891,  16.25916675,  21.8946076 ,
         24.48061965,  17.46917214,  29.46749902,  18.31930713,
         29.48097438,  23.71328736],
       [ 87.06206799,  54.01069606,  53.39761298,  71.96161928,
         74.06748364,  57.34489197,  82.29352385,  56.71556221,
         99.84931023,  79.56132672],
       [148.69529194,  94.59908321,  90.53605921, 122.02863097,
        123.65434763,  97.2206118 , 135.11954868,  95.11181729,
        170.21764608, 135.40936607],
       [210.32851589, 135.18747036, 127.67450545, 172.09564266,
        173.24121162, 137.09633163, 187.94557351, 133.50807237,
        240.58598193, 191.25740543],
       [271.96173984, 175.77585751, 164.81295168, 222.16265435,
        222.82807561, 176.97205146, 240.77159834, 171.90432745,
        310.95431778, 247.10544478],
       [333.59496379, 216.36424466, 201.95139791, 272.22966604,
        272.4149396 , 216.84777129, 293.59762317, 210.30058253,
        381.32265363, 302.95348414],
       [39

Problem 2: Conceptual Questions

1. What are some causes of overfitting? How do we diagnose and treat overfitting in
regression models?

    Overfitting can be caused by many things.
    Concretely the model remembers the training data instead of learning it.
    One cause is that the model is to complex, which means that it has to many features.
    Another cause is that the training data does not represent the test data.

    A way to evaluate a model is to divide its data intro two categories, test and train.
    Train data is used during training.
    Hopefully the model learns the pattern of this data.
    We use the test data to evaluate the model after training.
    This can lets us know if the whether the model has memorized or learned the data.
    Its essential that the model has not seen the test data, as this defeats the purpose of it.

    Overfitting can be diagnosed by comparing test and train results.
    If the model does substantially better on the train data, its overfitting.

    A way of treating overfitting in regression models is to use regularization.
    Regularization adds the weights of the model to the loss/error, and multiplies it by a hyperparameter.
    Regularization ensures that the weights dont get converge to high values.
    Another way of treating overfitting is to reduce the models complexity and
    making sure that the train data represents the test data in a good way.


2. What are the advantages and disadvantages of using ridge regression and lasso
regression? How are these regressions different?

    Flatere graf, x^2 og |x|

Problem 3: Machine Learning Regression Problem
The data in the file housedata.csv are collected from 1,000 homes being sold in Oslo. The
response variable of interest is the Price (price of the house). The input variables are
bedrooms, sqft_living (the living space area), sqft_lot (the area of the land the house sits on),
floors (the number of levels of the house), sqft_above (area of the house excluding the
basement), sqft_basement (basement area).

In [94]:
# 1. Use Multilinear Regression (MLR) and Decision Tree Regressor to build a regression
# model for prediction of house prices?

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model, tree, preprocessing
from sklearn.metrics import r2_score, mean_squared_error

df = pd.read_csv('C:/Users/mathi/Desktop/MLExam/housedata.csv', sep=';')

y = df['price']
X = df[['bedrooms', 'sqft_living', 'sqft_lot', 'floors', 'sqft_above', 'sqft_basement']]


min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(X)
X = pd.DataFrame(x_scaled)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)


DTR_model = tree.DecisionTreeRegressor()
DTR_model = DTR_model.fit(X_train, y_train)

MLR_model = linear_model.LinearRegression()
MLR_model = MLR_model.fit(X_train, y_train)

2. Perform Model Evaluation using two metrics: Root Mean Squared Error and
Coefficient of Determination? Which of the two regression models is better MLR or
Decision Tree?

In [95]:
DTR_predictions = DTR_model.predict(X_test)
MLR_predictions = MLR_model.predict(X_test)

print('DTR r2: %s'% r2_score(y_test, DTR_predictions))
print('DTR mse: %s'% mean_squared_error(y_test, DTR_predictions))

print('MLR r2: %s'% r2_score(y_test, MLR_predictions))
print('MLR mse: %s'% mean_squared_error(y_test, MLR_predictions))


# MLR is better the better regression model on this problem

DTR r2: 0.25087465508181706
DTR mse: 78219563956.956
MLR r2: 0.5741176142088571
MLR mse: 44468305256.93878


Problem 4: Deep Learning Problem Using Keras

In [96]:
df = pd.read_csv("C:/Users/mathi/Desktop/MLExam/train.csv")

df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            5000 non-null   object 
 1   Item_Weight                4182 non-null   float64
 2   Item_Fat_Content           5000 non-null   object 
 3   Item_Visibility            5000 non-null   float64
 4   Item_Type                  5000 non-null   object 
 5   Item_MRP                   5000 non-null   float64
 6   Outlet_Identifier          5000 non-null   object 
 7   Outlet_Establishment_Year  5000 non-null   int64  
 8   Outlet_Size                3561 non-null   object 
 9   Outlet_Location_Type       5000 non-null   object 
 10  Outlet_Type                5000 non-null   object 
 11  Item_Outlet_Sales          5000 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 468.9+ KB


In [99]:
df[df['Item_Weight'] is None].head()


Empty DataFrame
Columns: [Item_Identifier, Item_Weight, Item_Fat_Content, Item_Visibility, Item_Type, Item_MRP, Outlet_Identifier, Outlet_Establishment_Year, Outlet_Size, Outlet_Location_Type, Outlet_Type, Item_Outlet_Sales]
Index: []